# Daroach Tech Engine Docker Compose File
# My use of Jwilder's nginx-proxy and Jrcs's Letsencrypt Companion
# Author: Gagan Daroach gagandaroach@gmail.com
# Date: March 10 2019
version: '3'

networks:
  daroachnetwork:
    external: true

services:
  nginx-proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    networks:
      - daroachnetwork
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
    networks:
      - daroachnetwork

  portainer:
    restart: unless-stopped
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/romans/portainer:/data
    environment:
      - VIRTUAL_HOST=portainer.daroach.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=portainer.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    command: -H unix:///var/run/docker.sock
    networks:
      - daroachnetwork
    ports:
    - "9000:9000"

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs: