#daroach.net Docker Compose File.
#Author: Gagan Daroach
#Date: Jan 31 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  cloudnetwork:
  
services:
  #next cloud maria db
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${MOUNT_POINT}/mariadb:/var/lib/mysql
    env_file:
      - db.env
      - db-pass.env
    networks:
      - cloudnetwork

  #redis cache
  redis:
    image: redis:alpine
    restart: always
    networks:
      - cloudnetwork

  #next cloud service
  nextcloud:
    build: ./nextcloud_fpm
    restart: always
    volumes:
      - ${MOUNT_POINT}/nextcloud/html:/var/www/html
      - ${MOUNT_POINT}/nextcloud/config:/var/www/html
      - ${MOUNT_POINT}/nextcloud/apps:/var/www/html/custom_apps
      - ${MOUNT_POINT}/nextcloud/data:/var/www/html/data
      - ${MOUNT_POINT}/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    env_file:
      - db.env
      - cloud.env
    depends_on:
      - mariadb
      - redis
    networks:
      - cloudnetwork

  #nginx proxy -> connects to jwilder
  nginx_proxy:
    build: ./nginx_proxy
    restart: always
    volumes:
      - ${MOUNT_POINT}/nextcloud/html:/var/www/html:ro
      - ${MOUNT_POINT}/nextcloud/config:/config
    environment:
      - VIRTUAL_HOST=cloud.daroach.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    depends_on:
      - nextcloud
    networks:
      - daroachnetwork
      - cloudnetwork