#daroach.net Docker Compose File.
#Author: Gagan Daroach
#Date: Jan 31 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  network:
    internal: true

services:
  #next cloud maria db
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${MOUNT_POINT}/mariadb:/var/lib/mysql
    env_file:
      - db.env
      - db-pass.env
    networks:
      - network

  #next cloud service
  nextcloud:
    build: ./nextcloud_fpm
    restart: always
    volumes:
      - ${MOUNT_POINT}/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
    env_file:
      - db.env
      - cloud.env
    depends_on:
      - mariadb
    networks:
      - network

  #nginx proxy -> connects to jwilder
  nginx_proxy:
    build: ./nginx_proxy
    restart: always
    volumes:
      - ${MOUNT_POINT}/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.daroach.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    depends_on:
      - nextcloud
    networks:
      - daroachnetwork
      - network

  # nextcloud cron job
  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ${MOUNT_POINT}/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - mariadb
    networks:
      - network