#daroach.net Docker Compose File.
#Author: Gagan Daroach
#Date: Jan 31 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  
services:
  #next cloud maria db
  cloud_db_service:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /ChandVolume/Cloud/mariadb:/var/lib/mysql
    env_file:
      - db.env
      - db-pass.env
    networks:
      - daroachnetwork

  #redis cache
  cloud_redis:
    image: redis:alpine
    restart: always
    networks:
      - daroachnetwork

  #next cloud service
  cloud_service:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /ChandVolume/Cloud/nextcloud/html:/var/www/html
      - /ChandVolume/Cloud/nextcloud/config:/config
      - /ChandVolume/Cloud/nextcloud/data:/data
    environment:
      - MYSQL_HOST=cloud_db_service
      - REDIS_HOST=cloud_redis
    env_file:
      - db.env
    depends_on:
      - cloud_db_service
      - cloud_redis
    networks:
      - daroachnetwork

  #nginx proxy -> connects to jwilder
  cloud_proxy:
    build: ./cloud_proxy
    restart: always
    volumes:
      - /ChandVolume/Cloud/nextcloud/html:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.daroach.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    depends_on:
      - cloud_service
    networks:
      - daroachnetwork

  #cron scraper
  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /ChandVolume/Cloud/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - cloud_db_service
      - cloud_redis
    networks:
      - daroachnetwork