#daroach.net Docker Compose File.
#Author: Gagan Daroach
#Date: Jan 31 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  backend:
    internal: true

services:
  #next cloud maria db sql server 
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: "no"
    volumes:
      - ${MOUNT_POINT}/mariadb:/var/lib/mysql
    env_file:
      - db.env
      - db-pass.env
    networks:
      - backend

  # redis ram cache
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend

  # next cloud main service
  nextcloud:
    build: ./nextcloud_apache
    restart: "no"
    volumes:
      - ${MOUNT_POINT}/nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=cloud.daroach.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cloud.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    env_file:
      - db.env
      - cloud.env
    depends_on:
      - mariadb
      - redis
    networks:
      - backend
      - daroachnetwork

  # nextcloud cron job
  cron:
    image: nextcloud:apache
    restart: "no"
    volumes:
      - ${MOUNT_POINT}/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis
    networks:
      - backend
