#daroach.net Docker Compose File.
# this runs my media collection
#Author: Gagan Daroach
#Date: May 25 2019

version: "3"

networks:
  daroachnetwork:
    external: true
  backend:
    internal: true

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - VIRTUAL_HOST=media.daroach.net
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=media.daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - ADVERTISE_IP=https://media.daroach.net/
      # - PLEX_CLAIM=claim-QQ_Rt-gCXt6JrTRK4T_g
      # - ADVERTISE_IP=http://localhost:32400/
    volumes:
      - ${PLEX_MOUNTPOINT}/config:/config
      - ${PLEX_MOUNTPOINT}/temp:/transcode
      - ${PLEX_MOUNTPOINT}/data:/data
    networks:
      - daroachnetwork
      - backend