version: "3"

networks:
  daroachnetwork:
    external: true

services:
  nginx-daroachnet:
    restart: always
    image: nginx
    environment:
      - VIRTUAL_HOST=daroach.net
      - VIRTUAL_NETWORK=daroachnetwork
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=daroach.net
      - LETSENCRYPT_EMAIL=gagandaroach@gmail.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
      - /srv/webroot:/webroot
    ports: 
      - 80:80
    networks: 
      - daroachnetwork